# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000
set -g display-panes-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# (OS X) Fix pbcopy/pbpaste for old tmux versions (pre 2.6)
set -g default-command "/usr/bin/env nu"

# Upgrade $TERM
set -g default-terminal "screen-256color"

# Emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# List of plugins
unbind-key -n C-a
set -g prefix C-Space
bind-key -N "go to most recent window" C-Space last-window
bind-key -N "Open command palette" Space run-shell "~/.config/tmux/plugins/tmux-palette/bin/tmux-palette.sh"
# set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
# set -g @plugin "alexwforsythe/tmux-which-key"
set -g @plugin "eduwass/tmux-palette"
set -g @plugin 'Morantron/tmux-fingers'
set -g @fingers-key P
set -g @plugin "tmux-plugins/tmux-cowboy"
set -g @plugin "sainnhe/tmux-fzf"
set -g @plugin "gufranco/tmux-tiling-revamped"

set -g @tiling_revamped_default_layout "spiral"
set -g @tiling_revamped_auto_apply 1


# Initialize tpack (keep this line at the very bottom of tmux.conf)
run 'tpack init'
set -s command-alias layout-menu='run-shell "~/.config/tmux/plugins/tmux-tiling-revamped/src/tiling.sh pick"'
bind-key -N "Toggle monocle layout"  M run-shell "~/.config/tmux/plugins/tmux-tiling-revamped/src/tiling.sh layout monocle"
bind-key -N "move window left" h swap-window -d -t :-1
bind-key -N "move window right" l swap-window -d -t :+1
bind-key -N "previous window" p previous-window
# to avoid misses when rapidly switchnig window
bind-key -N "previous window" C-p previous-window
bind-key -N "next window" C-n next-window
